### ISSUE TITLE
Need collision detection and response system

### ISSUE THREAD

**Issue by zan-xhipe** [davexunit/guile-2d#13]
Most games require some form of collision detection. I would like to propose a system similar to what I have in https://github.com/blob626/square-man.

At the moment it uses a grid for spatial partitioning. This could easily be changed. It supports handling the start of a collision,  a continuing  collision, and the end of a collision. At the moment it just uses the sprite's size to check for collision. (I didn't notice rect.scm until today. I'm going to change square-mans collisions to bounding boxes now) 

I would be happy to work on this if you think its needed, but I'm just not sure how the user should interact with the collision system. Ideally they should just define the collision response handler, and give that to the scene. At the moment though they also need to define dimensions for the grid, how to get objects that can collide, and how to get objects sprites. Some of this will probably fall away once there is a scene graph and/or if a different spatial partitioning is used. (but grid is easy and for the type of game square-man is going to be, good enough)

**Comment by Halfwake** [comment]
EDIT: Oh right, you moved. Let me try there.

If it helps, I have a quad tree module written in Common Lisp. I can port it over, but I need to setup my guile environment and find some time first. https://github.com/Halfwake/cl-quad

**Comment by davexunit** [comment]
Thanks for sharing the code.  That makes 2 CL quadtree implementations that I know of.  From what I can see, this implementation uses a mutable quadtree.  In Sly (the new name for guile-2d), the quadtree _must_ use a purely functional data structure.  I've been meaning to look into how to implement a persistent quad tree, but haven't gotten around to it.

**Comment by Halfwake** [comment]
Are you sure my implementation isn't purely functional? There is no use of assignment operators. Methods return new quad trees instead of changing an existing tree. The slots for all classes are read only. It might even be a persistent tree. When a method creates a new tree, it uses references to the last tree without making copies.

**Comment by davexunit** [comment]
In that case I didn't read the code carefully enough! Thanks for explaining. I would love to see it implemented in Guile.

I'd be curious about the performance profile of it as well.  I imagine the time complexity for read/write are different than a mutable quad tree.
